site_name: Lydie
site_url: https://lydie.7kayoh.net/
repo_name: 7kayoh/Lydie
repo_url: https://github.com/7kayoh/lydie
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Dark theme
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Light theme
  font:
    text: Figtree
    code: Overpass Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

  language: en

plugins:
  - search
  - tags:
      tags_file: Tags.md
  - glightbox

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      title: On this page
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

nav:
  - Home: index.md
  - Tutorials:
    - Installing Lydie: Tutorials/InstallingLydie.md
    - Using Lydie: Tutorials/UsingLydie.md
    - Importing Lydie: Tutorials/ImportingLydie.md
  - Components:
    - Controls:
      - Buttons:
        - Components/Controls/Buttons/BaseButton.md
        - Components/Controls/Buttons/TextButton.md
        - Components/Controls/Buttons/IconButton.md
        - Components/Controls/Buttons/IconTextButton.md
        - Components/Controls/Buttons/AppBarButton.md
        - Components/Controls/Buttons/AppTabBarButton.md
      - Components/Controls/Checkbox.md
      - Components/Controls/Slider.md
      - Components/Controls/TextField.md
      - Components/Controls/Toggle.md
    - View:
      - Components/View/AppTabBar.md
      - Components/View/BottomAppBar.md
      - Components/View/ToolTip.md
      - Components/View/TopAppBar.md
      - Components/View/Window.md
    - Misc:
        - Components/Divider.md
        - Components/Shadow.md
  - Modules:
    - Modules/Constants.md
    - Modules/EnumList.md
    - Modules/Icons.md
    - Modules/Scheme.md
    - Modules/SharedStates.md
  - Tags: Tags.md

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/7kayoh/lydie
    - icon: fontawesome/brands/discord
      link: https://discord.gg/JSHRQkrafN

copyright: Copyright &copy; 2021 - 2024 7kayoh

extra_css:
  - stylesheets/theme.css