[package]
name = "7kayoh/lydie"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Fusion = "plainsour/lemon@0.3.0-dev.5.8"