-- 7kayoh
-- Dark.lua
-- 03 February 2022
return {
	Elevation = {
		Color3.fromRGB(0, 0, 0),
		Color3.fromRGB(20, 20, 20),
		Color3.fromRGB(25, 25, 25),
		Color3.fromRGB(30, 30, 30),
	},
	Typography = {
		HeroLarge = { Font = Enum.Font.GothamBold, Size = 28 },
		Hero = { Font = Enum.Font.GothamMedium, Size = 25 },
		Header = { Font = Enum.Font.GothamBold, Size = 14 },
		Subheader = { Font = Enum.Font.Gotham, Size = 14 },
		Body = { Font = Enum.Font.Gotham, Size = 16 },
		Button = { Font = Enum.Font.GothamBold, Size = 16 },
		Secondary = { Font = Enum.Font.GothamMedium, Size = 14 },
		Caption = { Font = Enum.Font.GothamBold, Size = 14 },
	},
	Color = {
		Red = Color3.fromRGB(199, 35, 35),
		Green = Color3.fromRGB(74, 224, 106),
		Blue = Color3.fromRGB(93, 162, 241),
		Amber = Color3.fromRGB(255, 201, 85),
		Orange = Color3.fromRGB(255, 127, 77),
		Pink = Color3.fromRGB(255, 134, 200),
		Purple = Color3.fromRGB(188, 146, 255),
		Indigo = Color3.fromRGB(131, 104, 255),
		Teal = Color3.fromRGB(70, 243, 188),
		Mint = Color3.fromRGB(42, 223, 211),
		Mono = {
			Color3.fromRGB(0, 0, 0),
			Color3.fromRGB(25, 25, 25),
			Color3.fromRGB(50, 50, 50),
			Color3.fromRGB(75, 75, 75),
			Color3.fromRGB(150, 150, 150),
			Color3.fromRGB(200, 200, 200),
			Color3.fromRGB(225, 225, 225),
			Color3.fromRGB(240, 240, 240),
			Color3.fromRGB(255, 255, 255),
		},
		Text = {
			Primary = Color3.fromRGB(220, 220, 220),
			Secondary = Color3.fromRGB(150, 150, 150),
			Tertiary = Color3.fromRGB(100, 100, 100),
		},
		Divider = Color3.fromRGB(60, 60, 60),
	},
}
