-- 7kayoh
-- SolarizedDark.lua
-- 03 February 2022
return {
	Elevation = {
		Color3.fromHex("002b36"),
		Color3.fromHex("002b36"),
		Color3.fromHex("073642"),
		Color3.fromHex("073642"),
	},
	Typography = {
		HeroLarge = { Font = Enum.Font.Ubuntu, Size = 28 },
		Hero = { Font = Enum.Font.Ubuntu, Size = 25 },
		Header = { Font = Enum.Font.Ubuntu, Size = 14 },
		Subheader = { Font = Enum.Font.Ubuntu, Size = 14 },
		Body = { Font = Enum.Font.Ubuntu, Size = 16 },
		Button = { Font = Enum.Font.Ubuntu, Size = 16 },
		Secondary = { Font = Enum.Font.Ubuntu, Size = 14 },
		Caption = { Font = Enum.Font.Ubuntu, Size = 14 },
	},
	Color = {
		Red = Color3.fromHex("dc322f"),
		Green = Color3.fromHex("859900"),
		Blue = Color3.fromHex("268bd2"),
		Amber = Color3.fromHex("b58900"),
		Orange = Color3.fromHex("cb4b16"),
		Pink = Color3.fromRGB(255, 51, 170),
		Purple = Color3.fromHex("6c71c4"),
		Indigo = Color3.fromHex("d33682"),
		Teal = Color3.fromRGB(70, 243, 188),
		Mint = Color3.fromRGB(42, 223, 211),
		Mono = {
			Color3.fromRGB(0, 0, 0),
			Color3.fromRGB(25, 25, 25),
			Color3.fromRGB(50, 50, 50),
			Color3.fromRGB(75, 75, 75),
			Color3.fromRGB(150, 150, 150),
			Color3.fromRGB(200, 200, 200),
			Color3.fromRGB(225, 225, 225),
			Color3.fromRGB(240, 240, 240),
			Color3.fromRGB(255, 255, 255),
		},
		Text = {
			Primary = Color3.fromHex("fdf6e3"),
			Secondary = Color3.fromHex("eee8d5"),
			Tertiary = Color3.fromHex("fdf6e3"),
		},
		Divider = Color3.fromHex("657b83"),
	},
}
