return {
    Controls = {
        AppBarButton = require(script.Controls.AppBarButton),
        AppTabBarButton = require(script.Controls.AppTabBarButton),
        BaseButton = require(script.Controls.BaseButton),
        Checkbox = require(script.Controls.Checkbox),
        ColorPicker = require(script.Controls.ColorPicker),
        IconButton = require(script.Controls.IconButton),
        Icons = require(script.Controls.Icons),
        IconTextButton = require(script.Controls.IconTextButton),
        Slider = require(script.Controls.Slider),
        TextButton = require(script.Controls.TextButton),
        TextField = require(script.Controls.TextField),
        Toggle = require(script.Controls.Toggle),
    },

    Views = {
        AppTabBar = require(script.Views.AppTabBar),
        BottomAppBar = require(script.Views.BottomAppBar),
        ToolTip = require(script.Views.ToolTip),
        TopAppBar = require(script.Views.TopAppBar),
        Window = require(script.Views.Window)
    },

    Divider = require(script.Divider),
    Shadow = require(script.Shadow),
}